version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/node/mukesh
permissions:
 - object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: ubuntu
